application: seekword
version: 1
runtime: python
api_version: 1

handlers:

- url: /client/css/
  static_dir: client/css

- url: /client/js/
  static_dir: client/js     
    
- url: /client/index.html
  static_dir: client/index.html     
   
- url: /.*
  script: main.py